export const GET_POKEMONS_REQUEST = 'GET_POKEMONS_REQUEST'
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS'
export const SET_POKEMONS = 'SET_POKEMONS'
export const FILTER_POKEMONS = 'FILTER_POKEMONS'
