export const REQUEST_POKEMONS = 'REQUEST_POKEMONS'
export const RECEIVE_POKEMONS = 'RECEIVE_POKEMONS'
export const REQUEST_SELECTED_POKEMON = 'REQUEST_SELECTED_POKEMON'
export const RECEIVE_SELECTED_POKEMON = 'RECEIVE_SELECTED_POKEMON'
